/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppBrand: typeof import('./src/components/core/AppBrand.vue')['default']
    AppCard: typeof import('./src/components/core/AppCard.vue')['default']
    AppHeader: typeof import('./src/components/layout/AppHeader.vue')['default']
    AppIcon: typeof import('./src/components/core/AppIcon.vue')['default']
    AppInput: typeof import('./src/components/core/AppInput.vue')['default']
    AppSkeleton: typeof import('./src/components/core/AppSkeleton.vue')['default']
    AppStatistic: typeof import('./src/components/core/AppStatistic.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
